// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGMt3oxGU7UaNOXlXOBj2n7zewrTRu8k8',
    appId: '1:649477606580:web:5067a182da60d0ae2d5be1',
    messagingSenderId: '649477606580',
    projectId: 'geminiaiproject-f6dd5',
    authDomain: 'geminiaiproject-f6dd5.firebaseapp.com',
    storageBucket: 'geminiaiproject-f6dd5.appspot.com',
    measurementId: 'G-FE38SET3M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVnx6Z7dKtCm0UGYECkKaTujKIpsuvgY',
    appId: '1:649477606580:android:34136010e4dd816e2d5be1',
    messagingSenderId: '649477606580',
    projectId: 'geminiaiproject-f6dd5',
    storageBucket: 'geminiaiproject-f6dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmU3wowKmsteA0Nngk6rBp60ELrPEZ0_w',
    appId: '1:649477606580:ios:aa359db9cef04b092d5be1',
    messagingSenderId: '649477606580',
    projectId: 'geminiaiproject-f6dd5',
    storageBucket: 'geminiaiproject-f6dd5.appspot.com',
    iosBundleId: 'com.example.chatAi',
  );
}
